SELECT * FROM EPL;
SELECT DISTINCT CLUB FROM EPL;
SELECT * FROM EPL WHERE Club = 'Liverpool FC';

-- QUERY 1 : TOP 3 POSSESSION BASED TEAMS(TEAMS HAVING MORE BALL POSSESSION)

SELECT * FROM EPL;
-- SHOWS POSSESSION FOR ALL THE CLUBS IN EPL
SELECT CLUB, SUM(PASSES_ATTEMPTED) AS POSSESSION FROM EPL GROUP BY CLUB;
 -- DISPLAYS TOP 3 CLUBS WITH POSSESSION
SELECT CLUB, SUM(PASSES_ATTEMPTED) AS POSSESSION FROM EPL GROUP BY CLUB ORDER BY POSSESSION DESC LIMIT 3;

-- QUERY 2 : BEST PLAYMAKERS( PLAYERS WITH HIGH CHANCE CREATION RATIO PER MATCH)

SELECT * FROM EPL;
-- SHOWS PLAYERS WITH MOST ASSISTS
SELECT NAME,CLUB,ASSISTS FROM EPL ORDER BY ASSISTS DESC;
-- SHOWS PLAYERS WITH AVERAGE ASSITS PER MATCH
SELECT NAME,CLUB,ASSISTS, ROUND(ASSISTS/MATCHES,2) AS Avg_assits_per_match FROM EPL WHERE ASSISTS > 0 GROUP BY NAME;
-- SHOWS TOP 10 PLAYERS WITH AVERAGE ASSITS PER MATCH
SELECT NAME,CLUB,ROUND(ASSISTS/MATCHES,2) AS Avg_assits_per_match 
FROM EPL WHERE ASSISTS > 0 GROUP BY NAME ORDER BY Avg_assits_per_match DESC LIMIT 10; 

-- QUERY 3 : TOP 5 MOST AGGRESSIVE TEAMS ( TEAMS WITH MOST FOULS COMMITTED PER MATCH RATIO)

SELECT * FROM EPL;
-- FOULS COMMITTED BY EACH CLUB
SELECT CLUB, SUM(Yellow_Cards) FROM EPL GROUP BY CLUB ORDER BY SUM(Yellow_Cards);
-- TOP 5 TEAMS WITH MOST FOULS COMMITTED 
SELECT CLUB, SUM(Yellow_Cards) FROM EPL GROUP BY CLUB ORDER BY SUM(Yellow_Cards) DESC LIMIT 5;
-- FOULS COMMITTED PER MATCH RATIO BY EACH CLUB 
SELECT CLUB, SUM(Yellow_Cards) ,Round(SUM(Yellow_Cards)/Matches,2) AS Fouls_per_match FROM EPL GROUP BY CLUB;
-- TOP 5 TEAMS WITH MOST FOULS COMMITTED PER MATCH RATIO
SELECT CLUB, SUM(Yellow_Cards) ,Round(SUM(Yellow_Cards)/Matches,2) AS Fouls_per_match 
FROM EPL GROUP BY CLUB ORDER BY Fouls_per_match DESC LIMIT 5;

-- QUERY 4: TOP 3 MOST IMPACTFUL PLAYERS( PLAYERS WITH G/A IN LESS TIME)

SELECT * FROM EPL;
-- PLAYERS WITH MATCHES LESS THAN 20
SELECT NAME, CLUB, MATCHES, STARTS,MINS, GOALS,ASSISTS
FROM EPL
WHERE MATCHES < 20;
-- TOP 3 MOST IMPACTFUL PLAYERS
SELECT NAME, CLUB, MATCHES, STARTS,MINS, GOALS,ASSISTS,(GOALS + ASSISTS) AS goals_assists
FROM EPL
WHERE MATCHES < 20 AND GOALS > 6 ORDER BY goals_assists DESC;
